n = input("number of samples:")
% w = 0:((2*pi)/n):(2*pi)
w = 0:0.1:2*pi
h1 = zeros(1,length(w))
for i=1:length(w)
  h1(i) = 1/(1-(0.9*exp(-j*w(i))))
endfor
mag1 = abs(h1)
phase1 = angle(h1)
subplot(2,1,1)
plot(w,mag1,'b')
xlabel("frequency")
ylabel("magnitude")
title("transfer function")
subplot(2,1,2)
plot(w,phase1,'r')
xlabel("frequency")
ylabel("phase")
title("transfer function")
